---
- hosts: all
  vars:
      kernel_pkg_path: "{{ kernel_pkg_path }}"
      kernel_pkg: "{{ kernel_pkg }}"
  tasks:
    - name: copy kernel inside DUTs
      copy:
        src: "{{ kernel_pkg_path }}"
        dest: /root/

    - name: install kernel package
      yum:
        name: "/root/{{ kernel_pkg }}"
        state: present

    # initramfs is also generateed automatically by installator
    # This is done automatically by installator
#    - name: regenerate GRUB configuration
#      command: grub2-mkconfig -o /boot/grub2/grub.cfg

    - name: set default kernel to the installed one (only for next boot)
      command: grub2-reboot 0

    - name: get current default kernel using grubby
      command: grubby --default-kernel
      register: current_default_kernel

    - name: "current default kernel (grub)"
      debug: msg="{{ current_default_kernel.stdout }}"

    - name: enforce system reboot on panic after N seconds
      command: grubby --args="panic=10" --update-kernel=ALL

    - name: reboot system into newly installed kernel
      reboot:
        reboot_timeout: 600 # 10 minutes

    - name: running kernel version
      debug:
        msg: "{{ ansible_kernel }}"
