---
- hosts: all
  tasks:
    - name: Test connection
      ping:

    - name: Ensure a list of packages installed
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - grubby
